version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "15432:5432"
    volumes:
      - /data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "phillrog@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
  
  app:
    working_dir: /home/app
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    image: node:10.12.0
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    environment:
      DB_HOST: db
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge